### ISSUE TITLE
TAB autocompletion for /join outputs

### ISSUE THREAD

**Issue by CyberiumShadow** [GusCaplan/retrocord#9]
http://i.imgur.com/TEEPCTr.gifv

As seen in the above gif, doing `/join [TAB]` outputs all the channels and guilds that you are part of.

An issue with that is that it obviously spams the readout.

A suggestion could be to only list the channels for each guild WHEN you are within that guild.

**Comment by GusCaplan** [comment]
cannot be done with vorpal
